### ISSUE TITLE
Rails 6.1 throws deprecation warnings

### ISSUE THREAD

**Issue by hirowatari** [reidmorrison/rails_semantic_logger#116] opened 2020-12-31 17:37 UTC
### Summary
When upgrading from Rails 6.0.x to Rails 6.1 `rails_semantic_logger` now throws deprecation warnings (even if it's never used).

### Environment

Provide at least:
* Ruby Version.
2.6.6
* Rails Version.
6.1.0
* Semantic Logger Version.
4.7.4
* Rails Semantic Logger Version.
4.4.6
* Other Application/framework names and versions (e.g. Puma, etc.).
Puma: 5.1.1
* Rails configuration. Only need the settings related to Rails Semantic Logger and Semantic Logger.
none 
* Full Stack Trace, if an exception is being raised.
not a stack trace but some useful info when starting rails server
```bash
$ rails s
=> Booting Puma
=> Rails 6.1.0 application starting in development
=> Run `bin/rails server --help` for more startup options
2020-12-31 09:30:38.571764 W [619400:47163069954400] Rails -- DEPRECATION WARNING: Initialization autoloaded the constants ActionText::ContentHelper and ActionText::TagHelper.

Being able to do this is deprecated. Autoloading during initialization is going
to be an error condition in future versions of Rails.

Reloading does not reboot the application, and therefore code executed during
initialization does not run again. So, if you reload ActionText::ContentHelper, for example,
the expected changes won't be reflected in that stale Module object.

These autoloaded constants have been unloaded.

In order to autoload safely at boot time, please wrap your code in a reloader
callback this way:

    Rails.application.reloader.to_prepare do
      # Autoload classes and modules needed at boot time here.
    end

That block runs when the application boots, and every time there is a reload.
For historical reasons, it may run twice, so it has to be idempotent.

Check the "Autoloading and Reloading Constants" guide to learn more about how
Rails autoloads and reloads.
 (called from <main> at <redacted>/config/environment.rb:7)
```
Note:
* Issues reported here should be related to monkey patches applied to Rails to make it use Semantic Logger. 
* For other logging and appender related issues, please report the issue at [Semantic Logger](https://github.com/rocketjob/semantic_logger/issues.

Sorry I don't understand this well enough to know if this should be a Semantic Logger issue.  Please advise I should move this there.

### Expected Behavior

* Describe your expectation of how Semantic Logger should behave, perhaps by showing how the builtin Rails logger behaves.
No deprecation warning error raised
* Provide a standalone Ruby script or a link to an example repository that helps reproduce the issue.
A Default Rails 6.1 app with `rails_semantic_logger` in the gemfile.

### Actual Behavior

* Describe or show the actual behavior.
No deprecation warning raise
* Provide text or screen capture showing the behavior.
Provided above

**Comment by reidmorrison** [comment] 2021-01-06 20:44
Can you submit a Pull Request to fix the issue, yet is still backward compatible with Rails 5?

**Comment by hirowatari** [comment] 2021-01-07 17:44
@reidmorrison Sorry I can't.  I don't have the foggiest idea of how I'd fix it.

**Comment by artemave** [comment] 2021-05-20 07:51
Same problem. Also don't know what's causing it.

**Comment by lisbethw1130** [comment] 2021-06-07 09:18
I found that if I removed [this line](https://github.com/reidmorrison/rails_semantic_logger/blob/master/lib/rails_semantic_logger/extensions/rails/server.rb#L8) in extensions/rails/server.rb, everything will be fine, but then no log output on rails server

So I look for other logger and see how they did, and found out instead of using autoload to "cheat" ruby, they [unsubscribe](https://github.com/roidrage/lograge/blob/master/lib/lograge.rb#L105-L125) the original logger and [subscribe](https://github.com/roidrage/lograge/tree/master/lib/lograge/log_subscribers) their own logger

maybe we can try in this way?

**Comment by reidmorrison** [comment] 2021-06-16 19:46
We upgraded to Rails 6.1 and do not see the errors you mentioned above. This is our output:
~~~
% bin/rails s
=> Booting Rails
=> Booting Puma
=> Rails 6.1.3.2 application starting in development 
=> Run `bin/rails server --help` for more startup options
Puma starting in single mode...
* Puma version: 5.3.2 (ruby 3.0.1-p64) ("Sweetnighter")
*  Min threads: 5
*  Max threads: 5
*  Environment: development
*          PID: 76881
* Listening on http://127.0.0.1:3003
* Listening on http://[::1]:3003
Use Ctrl-C to stop
2021-06-16 19:45:12.145989 D [76881:puma threadpool 002 logger.rb:41] Rack -- Started -- { :method => "GET", :path => "/", :ip => "127.0.0.1" }
...
~~~

**Comment by artemave** [comment] 2021-06-17 10:08
In our case, this deprecation warning wasn't caused by semantic logger. Semantic logger simply makes it more visible. But otherwise the same warning appeared in `development.log` with rails stock logger.

The actual cause was referencing one of the rails constants (`AciontText` maybe?) in an initializer.

See also https://github.com/rails/rails/issues/36546

**Comment by reidmorrison** [comment] 2021-06-17 20:15
Thank you, will close this issue then.

**Closed by reidmorrison** 2021-06-17 20:15 UTC
Labels: awaiting feedback
